from typing import Any, Protocol

from codex_graph.models import FileAst


class GraphDatabase(Protocol):
    async def persist_file(self, path: str) -> str: ...

    async def persist_file_ast(self, fa: FileAst, file_path: str) -> None: ...

    async def ensure_ready(self) -> None: ...

    async def fetch_cypher(self, cypher: str, columns: int | None = None) -> list[tuple[Any, ...]]: ...

    async def get_file_by_id(self, file_uuid: str) -> tuple[str, str, str, str] | None: ...

    async def list_files(self, limit: int = 50) -> list[tuple[str, str, str, str]]: ...

    async def list_files_cursor(
        self,
        limit: int = 50,
        after_path: str | None = None,
        after_id: str | None = None,
        before_path: str | None = None,
        before_id: str | None = None,
    ) -> list[tuple[str, str, str, str]]: ...

    async def get_language_for_file(self, file_uuid: str) -> str: ...

    async def get_languages_for_files(self, file_uuids: list[str]) -> dict[str, str]: ...

    async def get_node_details(self, span_keys: list[str]) -> dict[str, tuple[Any, ...]]: ...

    async def ping(self) -> bool: ...

    async def dispose(self) -> None: ...
